Correct the usage of pointers of database objects
miyurud/jasminegraph pull request #225
Opened 2024-01-02 17:24 UTC by Ishad-M-I-M

Consider only after merging #224

2024-01-06 13:28 UTC, miyurud commented on src/performance/metrics/PerformanceUtil.h
> +    // static SQLiteDBInterface *sqlLiteDB;
Since these two lines are commented, lets delete those.

2024-01-06 13:34 UTC, Ishad-M-I-M commented on src/performance/metrics/PerformanceUtil.h
> +    // static SQLiteDBInterface *sqlLiteDB;
```suggestion
```

2024-01-06 13:34 UTC, Ishad-M-I-M commented on src/performance/metrics/PerformanceUtil.h
> +    // static PerformanceSQLiteDBInterface *perfDb;
```suggestion
```

2024-01-06 13:41 UTC, miyurud requested changes
Please address the PR comment

2024-01-06 15:51 UTC, thevindu-w commented on src/server/JasmineGraphServer.cpp
> +    delete jobScheduler;
Why not `this->sqlite` and other variables (with `this->`)?

2024-01-06 15:51 UTC, thevindu-w commented on src/performance/metrics/PerformanceUtil.cpp
> +    perfDb = new PerformanceSQLiteDBInterface();
If `PerformanceUtil::init()` is called multiple times, won't this cause a memory leak?

2024-01-06 15:51 UTC, thevindu-w commented on src/frontend/JasmineGraphFrontEnd.cpp
> +        JasmineGraphServer *jasmineServer = JasmineGraphServer::getInstance();
Is this variable `jasmineServer` used?

2024-01-06 15:51 UTC, thevindu-w commented on src/frontend/JasmineGraphFrontEnd.cpp
> +        JasmineGraphServer *jasmineServer = JasmineGraphServer::getInstance();
Is this variable `jasmineServer` used?

2024-01-07 12:38 UTC, miyurud approved these changes

2024-01-07 12:38 UTC, merged